# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Jihye Leee
baseurl:        ""
url:            "https://www.jihyeleee.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jihye Leee
  url:          https://jihyeleee.com/
  email:        iam.leejihye@gmail.com  
  github:       iamleejihye
  twitter:      hitchhikerj

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/iamleejihye/iamleejihye.github.io